
---
- name: Apache või HTTP teenuse paigaldamine klientmasinas
  hosts: webservers
  vars:
    apache_deb: apache2
    apache_red: httpd
    user_name: user #kasutajanimi
    public_html_dir: "/home/{{ user_name }}/public_html"

  tasks:
    - name: Paigaldame apache2 teenuse Debian masinatele
      package:
        name: "{{ apache_deb }}"
        state: latest
        update_cache: yes
      when:
        - ansible_os_family == "Debian"

    - name: Paigaldame http teenuse RedHat masinatele
      package:
        name: "{{ apache_red }}"
        state: latest
        update_cache: yes
      when:
        - ansible_os_family == "RedHat"

    - name: Loome public_html kausta kasutajale user
      file:
        path: "{{ public_html_dir }}"
        owner: "{{ user_name }}"
        group: "{{ user_name }}"
        mode: 0755
        state: directory

    - name: Enable'ime ja käivitame apache2 teenuse
      service:
        name: "{{ apache_deb if ansible_os_family == 'Debian' else apache_red }}"
        state: started
        enabled: yes

