#PHP 8.2 teenuse kliendiserveritele paigaldamise Ansible playbook.

---
- name: PHP 8.2 teenuse paigaldamine Debian ja CentOS masinatele
  hosts: webservers
  become: true #kõik käsud jooksevad root õigustega

  vars: #muutujad
    php_packages:
      Debian:
        - php8.2
        - php8.2-cli
        - php8.2-fpm
      RedHat:
        - php
        - php-cli
        - php-fpm
    apache_deb: apache2 #kasutatakse Debiani masina puhul
    apache_red: httpd #kasutatakse CentOS masina puhul
    user_name: user
    remi_repo_url: "https://rpms.remirepo.net/enterprise/remi-release-9.rpm" #Remi repo aadress

  tasks:

############################################################

#####Uuendame masinad

    - name: Uuenda Debiani masinatel kõik paketid
      apt:
        update_cache: yes
        upgrade: dist
      when: ansible_os_family == "Debian"

    - name: Uuenda CentOS masinatel kõik paketid
      dnf:
        name: '*'
        state: latest
      when: ansible_os_family == "RedHat"

#    - name: Import Remi GPG key
#      rpm_key:
#        state: present
#        key: https://rpms.remirepo.net/RPM-GPG-KEY-remi
#      when: ansible_os_family == "RedHat"

######Remi repo allalaadimine, paigaldamine ja seadistamine CentOS masinatel

    - name: Laeme alla Remi repo
      get_url:
        url: "{{ remi_repo_url }}"
        dest: "/tmp/remi-release.rpm"
        mode: '0644'
      when: ansible_os_family == "RedHat"

    - name: Paigaldame Remi repo
      command: "dnf install -y /tmp/remi-release.rpm --nogpgcheck"
      when: ansible_os_family == "RedHat"

    - name: Lubame PHP 8.2 mooduli CentOS masinatel
      command: dnf module enable php:remi-8.2 -y
      when: ansible_os_family == "RedHat"

#####PHP 8.2 teenuse paigaldamine ja käivitamine

    - name: PHP teenuse paigaldamine
      package:
        name: "{{ php_packages[ansible_os_family] }}"
        state: present

    - name: Lubame ja käivitame PHP-FPM teenuse
      service:
        name: "{{ 'php8.2-fpm' if ansible_os_family == 'Debian' else 'php-fpm' }}"
        state: started
        enabled: true

    - name: Teeme apache2/http teenusele restardi
      service:
        name: "{{ apache_deb if ansible_os_family == 'Debian' else apache_red }}"
        state: restarted

####################Iseseisev ülesanne1######################

    - name: Loome phpinfo.php faili
      copy:
        dest: /var/www/html/phpinfo.php
        content:
          <html>
            <body>
              <?php
                phpinfo();
              ?>
            </body>
          </html>
        owner: "{{ user_name }}"
        group: "{{ user_name }}"
        mode: '0644'

    - name: Paigaldab Apache PHP lisamooduli Debiani masinatele
      ansible.builtin.package:
        name: libapache2-mod-php
        state: present
      when: ansible_os_family == "Debian"

    - name: Teeme apache2/http teenusele restardi
      service:
        name: "{{ apache_deb if ansible_os_family == 'Debian' else apache_red }}"
        state: restarted
